# Copyright 2026 Hygon Information Technology Co., Ltd.
# SPDX-License-Identifier: BSD-3-Clause

"""Compatibility operator frontends backed by TurboPhysAI native providers."""

from .bev_pool import (
    BevPoolFunction,
    bev_pool,
    bev_pool_backward,
    bev_pool_forward,
    bev_pool_prepare,
    bev_pool_prepare_geometry,
)
from .sparse_conv import (
    IndiceConvFunction,
    IndiceMaxPoolFunction,
    fused_indice_conv_fp32,
    fused_indice_conv_half,
    get_indice_pairs,
    get_indice_pairs_2d,
    get_indice_pairs_3d,
    get_indice_pairs_4d,
    get_indice_pairs_grid_2d,
    get_indice_pairs_grid_3d,
    indice_conv_backward_fp32,
    indice_conv_backward_half,
    indice_conv_fp32,
    indice_conv_half,
    indice_maxpool_backward_fp32,
    indice_maxpool_backward_half,
    indice_maxpool_fp32,
    indice_maxpool_half,
    indice_conv,
    indice_maxpool,
)
from .voxelization import (
    DynamicScatterFunction,
    dynamic_point_to_voxel_backward,
    dynamic_point_to_voxel_forward,
    dynamic_scatter,
    dynamic_voxelize,
    hard_voxelize,
    voxelization_forward,
    voxelize,
)

__all__ = [
    "BevPoolFunction",
    "bev_pool",
    "bev_pool_forward",
    "bev_pool_backward",
    "bev_pool_prepare",
    "bev_pool_prepare_geometry",
    "dynamic_voxelize",
    "hard_voxelize",
    "voxelize",
    "voxelization_forward",
    "DynamicScatterFunction",
    "dynamic_point_to_voxel_forward",
    "dynamic_point_to_voxel_backward",
    "dynamic_scatter",
    "get_indice_pairs",
    "get_indice_pairs_2d",
    "get_indice_pairs_3d",
    "get_indice_pairs_4d",
    "get_indice_pairs_grid_2d",
    "get_indice_pairs_grid_3d",
    "IndiceConvFunction",
    "indice_conv",
    "indice_conv_fp32",
    "indice_conv_backward_fp32",
    "indice_conv_half",
    "indice_conv_backward_half",
    "fused_indice_conv_fp32",
    "fused_indice_conv_half",
    "indice_maxpool_fp32",
    "indice_maxpool_backward_fp32",
    "indice_maxpool_half",
    "indice_maxpool_backward_half",
    "IndiceMaxPoolFunction",
    "indice_maxpool",
]
